### ISSUE TITLE
Consider making them observable in V2

### ISSUE THREAD

**Issue by rbrundritt** [GeoJSON-Net/GeoJSON.Net#126]
For V2, it would be great if the geometries supported being observable objects which we could data bind. I was writing a .NET library recently where GeoJSON is the basic data object and wanted to bind it to a UI. I ended up having to create a set of wrapper geometries that were observable which was less than ideal.

**Comment by xfischer** [comment]
Hi @rbrundritt. Do you mean like the WPF way with observable collections and INotifyProperyChanged implementations ?
We should give it a try and test. I don’t know how this would/could affect Json deserialization. Any thoughts @matt-lethargic ?

**Comment by matt-lethargic** [comment]
Hi both, it's been years since I've dabbled in observables and INotifyPropertyChanged. 
My first thought is that this would be out of scope for the library. It's single purpose is to serialise/deserialise GeoJSON, adding observables starts to mix things up a lot more so I'd be hesitant to start adding in

**Comment by rbrundritt** [comment]
I thought this might be the case. Was hoping to be able to avoid having to transform the data from one object to another. I'm also using NetTopologySuite and have a similar issue there. No worries.
