### ISSUE TITLE
DbGeometry + PolygonConverter = WellKnownText 

### ISSUE THREAD

**Issue by Leon-O** [GeoJSON-Net/GeoJSON.Net#43]
Hi, I'm storing my polygon on MS SQL Server with EntityFramework's DbGeometry property. When I use the PolygonConverter I'm still getting the WKT format of the data, no the GeoJson.
```c#
        [JsonConverter(typeof (PolygonConverter))]
        public DbGeometry Coordenadas { get; set; }
```
```javascript
console.log(data.Options[0].Coordenadas);
```
![wkt](https://cloud.githubusercontent.com/assets/4379316/9426188/6bbae37c-48fe-11e5-8eac-d0bc1556bdb0.PNG)

Do I need to change my data type or create my own fork of this library?

**Comment by jbattermann** [comment]
Good morning!

the problem here is that you decorate an entire 'DbGeometry' property / instance with the PolygonConverter & that can't work - the PolygonConverter works with / on that plain GeoJson Polygon strings/structures.

So basically what you'd need is your own / DBGeometry JsonConverter, i.e. as a starting point see this [SO post](http://stackoverflow.com/questions/20926102/deserializing-dbgeometry-with-newtonsoft-json), even though that doesn't serialize to GeoJSON.. but as a general hint how to convert forward and backwards.

As this would be specific to System.Data(.Entity).Spatial I'd rather not put that in the core GeoJSON library. You can certainly either fork the library or create a new, separate project underneath [GeoJSON.Net.Contrib](https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib) i.e. 'GeoJSON.Net.Contrib.EntityFramework' and send over a PR there.

Cheers!
-J

**Comment by Leon-O** [comment]
Ok, thanks.
