### ISSUE TITLE
Array 

### ISSUE THREAD

**Issue by jphellemons** [GeoJSON-Net/GeoJSON.Net#53]
I have an array of GeoJson Points and it seems invalid at http://geojsonlint.com/

    List<Point> ar = new List<Point>();      
    foreach(DataRow dr in dt.Rows)
    {
        ar.Add((Point)MsSqlSpatialConvert.ToGeoJSONGeometry((SqlGeography)dr["SsLoc"]));
    }
    var serializer = new JsonSerializer();
    serializer.Serialize(Response.Output, ar.ToArray());

Perhaps the serializer should serialize arrays to **GeometryCollection** or maybe **FeatureCollection**
http://geojson.org/geojson-spec.html#geometry-collection

What are your thoughts? or what am I doing wrong? Looking forward to your response. 

![tweet](https://pbs.twimg.com/media/CgY0DPMWsAAKiC1.jpg:large)

**Comment by jbattermann** [comment]
Hello,

I think you're doing it wrong - you are creating a BCL List<Point> rather than a FeatureCollection (i.e. see https://github.com/GeoJSON-Net/GeoJSON.Net/blob/master/src/GeoJSON.Net.Tests/Feature/FeatureCollectionTests.cs#L53) and thereby working around the GeoJSON properties the FeatureCollection would add to the serialized Json, including the 'Type' property missing there.

What you're doing is handing over a BCL List<T> (the inner Point instances are correctly formatted, including the type property) to Json.Net and therefore just using standard Json.net serialization of Lists.

Try using it as shown above it that sample test and I think it should work as expected.

-J

**Comment by jphellemons** [comment]
Thank you @jbattermann 
If I understand it correctly, I should not add them to a List<Point> but to a FeatureCollection. As I am new to GeoJson, can you tell me why I should use a FeatureCollection rather than a GeometryCollection?

**Comment by jbattermann** [comment]
Sure thing @jphellemons. For a deeper understanding of GeoJSON and how to use and apply it, I'd suggest reading the [GeoJson Spec](http://geojson.org/geojson-spec.html), particularly the sections about Geometry and Feature Objects and collections.. and the https://datatracker.ietf.org/doc/draft-ietf-geojson/?include_text=1 goes into more details than the original spec.
