### ISSUE TITLE
Properties object on Geojson

### ISSUE THREAD

**Issue by lawrencegripper** [GeoJSON-Net/GeoJSON.Net#58]
I'd like to put together a pull request to expose out the properties objects, like in the example here  http://geojson.org/geojson-spec.html#examples, on the geojson objects I'm deserialising. Given the flexibility of the spec around properties I'd like to pull them in as a JObject which can be access. 

Any objections to me putting together this PR?

**Comment by jbattermann** [comment]
Hi Lawrence,

the [.Properties are currently already exposed](https://github.com/GeoJSON-Net/GeoJSON.Net/search?utf8=%E2%9C%93&q=Dictionary%3Cstring%2C+object%3E+Properties&type=Code) as `Dictionary<string, object>` - this `object` part isn't particularly nice from a type-safety / developer usability perspective but due to the GeoJSON's spec allowing all kinds of sub-object types there this was chosen.. even more so because Json.Net automatically treats those correctly (and [practically as JObjects](http://www.newtonsoft.com/json/help/html/SerializationGuide.htm#Objects)).. well on the serialization part - I am not entirely sure right now what happens on deserialization.. I _think_ they are deserialized as JObjects by default... I _think_.

Any kind of improvement is highly welcome, but what exactly would you want to change / improve?

**Comment by lawrencegripper** [comment]
Hi, 

Thanks for the quick reply, I think I'd missed the properties as I was looking at the "Geometry" class rather than the "Feature". Bit of a Doh moment. 

Potentially moving to a type of JObject or Dictionary<string,jobject> would allow code like below ..

Feature.Properties["prop1"].SelectToken("locationstats[0].height")

That being said I think I can work with the dictionary<string,object> if you'd rather avoid a breaking change for existing users.

**Comment by jbattermann** [comment]
No worries - the library itself is a bit.. well.. a bit of a mess so you certainly can overlook a few things here and there ;)

However, given that it already does have a certain installed base as it is today, I'd rather not change the dictionary's value type as it would unfortunately be a breaking change.

As I said - I think (I really haven't checked.. lately) - on deserialization JSON.Net does deserialize those objects of the .Properties dictionary into JObjects at least the complex types placed in there .. I would be surprised if it did it any other way.

If it does, you 'could' probably write an extension method that takes those .Properties and returns a Dictionary<string, JObject> and that I'd certainly pull into the library.

That's only a 'I think' kinda idea but if, and only if, it's something you want to do / would help in your own use case and send it as a PR, I'd merge it in :smile:

**Comment by lawrencegripper** [comment]
Sounds like a plan, I'll have a play tomorrow and put together a PR with an extension method if it works out well and is useful :)

**Comment by jbattermann** [comment]
:+1:

**Comment by matt-lethargic** [comment]
Hey @lawrencegripper, I'm just doing some house keeping, I noticed that this hasn't had any more comments for a while and you haven't submitted a PR. Can I close this or do you have more you'd like to add etc?

**Comment by lawrencegripper** [comment]
Hi, Sure - best to close this one out. I got things up and running but the result was very specific to our use case so didn't submit a PR in the end. Sorry should have come back and closed it off!

**Comment by matt-lethargic** [comment]
No worries about not closing it before. Glad things are working out.
