### ISSUE TITLE
Project is Dead (or up for grabs)

### ISSUE THREAD

**Issue by jbattermann** [GeoJSON-Net/GeoJSON.Net#68]
As the title says.. or well.. so does the the [Readme.md file](https://github.com/GeoJSON-Net/GeoJSON.Net/blob/master/README.md#-project-is-no-longer-maintained--up-for-grabs-).

If you're interested to take over the project and take good care of it, let me know.

Cheers,
-J

**Comment by hanssens** [comment]
@jbattermann Too bad man, you've done a great job so far. However, we've all been there and total respect for your decision on this one. 👍 

But, if you are willing, I'm hereby volunteering to take over the git project and NuGet feed. Would love to get my hands on fixing that dotnet-core stuff from my previous PR ;)

**Comment by matt-lethargic** [comment]
I'd like to throw my hand in as well, but also happy to just contribute. Have used this in a couple of big projects and would be a shame to see it die.

**Comment by jbattermann** [comment]
@hanssens & @matt-lethargic Thanks for the kind words and for stepping up 👍

Would it be alright for you two if I added you two as Members to the 'GeoJSON' org as members.. which would give you all the rights for the repository itself?

The NuGet package is currently under my personal account and so is the corresponding AppVeyor account / project etc.

What could / should we do about those two? I can / could keep it set up for building from a 'Release' branch or so based on an (to be created) appveyor.yml file (+ i.e. the dotnet core (powershell or so) build scripts) and (keep) it publishing to NuGet for those builds automatically.. for now.


@xfischer currently takes / took care of the -Contrib repository, so maybe he's also interested in chiming in a bit..

.. and if all goes well for a little while, I'd gladly hand over the github org & transfer the NuGet package ownership to you guys.. or you know.. whoever wants to carry the main 'burden' then :)

Would that be feasible for you?

**Comment by xfischer** [comment]
I'm still alive ! Yeah I took care of the SqlServer contrib, and I'm still in ! There's no known bugs, but I will contribute as I did before !
If you need any help from me let me know.
Respects Jörg, because GeoJson.net is used by some fellow of mine and is very useful to them.
And welcome to @hanssens and @matt-lethargic.

**Comment by matt-lethargic** [comment]
Hi guys!! Thanks for the warm welcome. It would be great to add us to the GeoJSON org. I've not used AppVeyor before, but have signed up and am looking at it now, I'm happy to move things over to my account if wanted to, @hanssens thoughts?

Also @hanssens do you want to take 'lead' on this or do you just want to do the core stuff? I'm happy to be the number two if you have some specific ideas where you'd like to take the project. Perhaps drop me an email if you want mattlethargic@gmail.com

**Comment by hanssens** [comment]
Good vibrations here, guys! Thumbs up to all here for being enthusiastic and swift in your responses; that's a great start. 

My opinion on everything stated:

**1. Ownership vs granting access**  
I also agree with @jbatterman's approach as a first step on giving access, rather than transferring ownership, is the way to go. Let's first have a look to see the dedication and collaboration of the team members, including myself, and see how it evolves from there. 

Transferring ownership can always be done later.

**2. Assign a lead**  
As @matt-lethargic mentions: one important part currently unaddressed is assigning the current "project lead". Obviously, no one wants cumbersome structures but in my experience it works quite well if someone makes the tough decisions and keep a general vision (governance) intact. 

Besides that, the lead should also manage the releases (CI with appveyor or not), NuGet packages, monitor and act on the issues, setup the milestones and follow up communication with the other contributors. 

I am fine with either contributing as a developer OR as giving a head start on this project as a lead perspective. But I'm reluctant to do both; that would be too time consuming for me. So, if no one steps up for the lead role, I am willing to take this up. But I also would be quite comfortable in taking the second role.   

How do you guys feel about this? 

**3. AppVeyor**  
I have no experience with AppVeyor. Having either this, or any another CI/CD system is just fine for me. Would personally opt for something free for open source, though. First task for the lead to decide ;)

--- 

For the sake of discussion, I took the libery in creating a (temp?) Gitter room to discuss this:
[https://gitter.im/GeoJSONNet](https://gitter.im/GeoJSONNet)

Please feel free to join...

**Comment by jbattermann** [comment]
Good evening everybody! Good vibes here indeed, thanks! And thanks a lot on working on the Issues "backlog" already today 👍 

I've gone ahead and added you to the GeoJSON.net Org's [Core Maintainers](https://github.com/orgs/GeoJSON-Net/teams/core-maintainers) & @xfischer to the [Contrib Maintainers](https://github.com/orgs/GeoJSON-Net/teams/contrib-maintainers) Teams which give you full write access etc to the corresponding repositories.

**Regarding CI / Appveyor**: it is free as in entirely free and unrestricted / limited for open source projects such as GeoJSON.Net and currently it basically builds for every pushed (batch of) commit and the NuGet deployment is done manually by me. This all works perfectly fine and almost out of the box with 'traditional' .sln/.csproj etc kind of projects, but to get it working with dotnet core etc some manual steps have to be added. There's a pretty [extensive tutorial up for the basics on their docs site](https://www.appveyor.com/docs/) and regarding the entire dotnet core etc pipeline, there's a [3rd party post explaining how things could be set up](http://www.michael-whelan.net/continuous-delivery-github-cake-gittools-appveyor/). But whatever you guys would prefer in the long run is fine with me.

The only 'secret' part is currently the NuGet.org API key to publish the package... and similarly to handing over the Github Org ownership, I'd say handing over the NuGet Id/Package ownership at the same time would make sense.. I'll prepare the transfer however and set up a new NuGet.org account just for the GeoJSON Package and transfer the ownership there already.. so its API key is separate from my personal one / other projects already.. so I could give you that one already once you've decided if / what CI pipeline to use.

**Regarding the Lead**
I'll step back regarding this one and let you guys decide who would want to do want or if some one else chimes in altogether.. the position /decision wouldn't have to be made right away.. no worries.. and just to make this clear.. if any of you decides to stop contributing/maintaing.. no worries, I certainly wouldn't be the one to judge ;) Anyway, take your time to decide who would want to be the lead here..

I got to run now, but I hope that all sounds good to you, too.

Cheers and and have a nice evening!
-J
